### ISSUE TITLE
input框内容关联选择框，切换选择框，重置input框data时，再切换值又展示了

### ISSUE THREAD

**Issue by zhangshuchen** [ecomfe/santd#114]
`<std-formitem
                class="sbiz-h-9 sbiz-mb-3"
                label="账号类型"
                >
                    <std-group name="radiogroup" value="{=accountType=}" on-change="handleChange" class="sbiz-bg-inherit">
                        <std-radio value="{{1}}">手机号</std-radio>
                        <std-radio value="{{2}}">百度账号</std-radio>
                    </std-group>
                </std-formitem>

                <std-formitem
                class="sbiz-h-9 sbiz-mb-6"
                label="{{accountMap[accountType]['label']}}"
                validateStatus="{{accountNameStatus}}"
                help="{{accountNameTips}}"
                >
                    <std-input placeholder="{{accountMap[accountType]['placeholder']}}" value="{=accountName=}" autocomplete="off" decorator="{{accountType === 1 ? phoneDecorator : accountNameDecorator}}" on-blur="checkAccount">
                    </std-input>
                </std-formitem>`

**Comment by zhangshuchen** [comment]
放在nextTip中进行更新没问题了，原因是？

**Comment by okaychen** [comment]
> 放在nextTip中进行更新没问题了，原因是？

数据变化了 DOM未更新，在nextTick里已解决
