### ISSUE TITLE
input-number 组件 precision 属性为0时失效

### ISSUE THREAD

**Issue by jqwang521** [ecomfe/santd#117]
`<s-input-number precision="{{0}}" >`

- 期望：正确设置数值精度为整数
- 实际现象：数值精度失效，可以输入任意小数
![image](https://user-images.githubusercontent.com/25954706/198295912-b8a0f244-4f09-4505-ade0-d162f2963035.png)

- santd版本：1.0.23
- 原因：
  在input-number 组件中，找到了如下代码
  <img width="554" alt="image" src="https://user-images.githubusercontent.com/25954706/198294480-af71b5fa-3b86-4709-a91b-f1686f472362.png">
  precision = 0时候，进入了后面的分支。

希望能修复这里的precision判空逻辑

- 同时找到了一个可以临时绕过的方案：
临时设置precision=0.1 来代替，原理：
<img width="190" alt="image" src="https://user-images.githubusercontent.com/25954706/198295608-3f7563b8-6d8f-4b6b-9e3e-2f3bf33c9ac7.png">

**Comment by okaychen** [comment]
已定位，小版本修复。也可以用 `precision="0"` 字符串零绕过判断
