### ISSUE TITLE
开发环境报错

### ISSUE THREAD

**Issue by liicos** [ecomfe/santd#5]
![image](https://user-images.githubusercontent.com/29332099/82651328-95090580-9c4e-11ea-899f-accf09109500.png)
![image](https://user-images.githubusercontent.com/29332099/82651574-e913ea00-9c4e-11ea-9bd3-daed7d8b86fe.png)

**Comment by ksky521** [comment]
这是因为windows下面拼路径用了`\`导致的，这个后续把hulk-san-loader换成san-loader会修复

**Comment by liicos** [comment]
啥时候换，现在还是报这个错误

**Comment by liicos** [comment]
> 这是因为windows下面拼路径用了`\`导致的，这个后续把hulk-san-loader换成san-loader会修复

啥时候换，现在还是报这个错误
