### ISSUE TITLE
Typography 报错， san 3.7.6+ 版本

### ISSUE THREAD

**Issue by BUPTlhuanyu** [ecomfe/santd#6]
排版组件Typography报错，在 computed 中 this.data.get() 报错，提示参数不能为空。
![image](https://user-images.githubusercontent.com/27213108/88005971-29072880-cb3d-11ea-8035-69ba19b0ff58.png)

需要修改为：
`                    clientRendered,
                    copyable,
                    getEllipsis
                } = this.data.get();
                // const clientRendered = this.data.get('clientRendered');
                // const copyable = this.data.get('copyable');
                // const getEllipsis = this.data.get('getEllipsis');
`

**Comment by jinzhan** [comment]
兄弟发个pr？
