### ISSUE TITLE
Tree组件能支持mouse事件么

### ISSUE THREAD

**Issue by Gavin-YYC** [ecomfe/santd#64]
比如mouseleave、mouseenter事件
其实也可以在slot=title中自己写on-mouse事件，但是在slot=title中，只可以拿到当前的title值，拿不到key等其他数据，所以也不能满足需求，最好在slot=title中，同时注入所有的当前item的数据

**Comment by Lohoyo** [comment]
以下这样是否满足需求？

```html
<s-tree-node key="0-0">
    <div slot="title" on-mouseover="onMouseover('0-0')">标题</div>
</s-tree-node>
```

**Comment by Gavin-YYC** [comment]
> 以下这样是否满足需求？
> 
> ```
> <s-tree-node key="0-0">
>     <div slot="title" on-mouseover="onMouseover('0-0')">标题</div>
> </s-tree-node>
> ```

示例看是没有问题的
但我是直接用的s-tree，传入的treeData，嵌套层级很多，这种怎么获取key呢

**Comment by Lohoyo** [comment]
那可以把 key 放进 title 里：

```html
<template>
    <s-tree treeData="{{treeData}}">
        <div slot="title" on-mouseover="onMouseover(title)">{{title | getRealTitle}}</div>
    </s-tree>
</template>

<script>
import {Tree} from 'santd';
export default {
    components: {
        's-tree': Tree
    },
    initData() {
        return {
            treeData:  [
                {
                    title: '标题一+0-0',
                    key: '0-0'
                },
                {
                    title: '标题二+0-1',
                    key: '0-1'
                }
            ]
        }
    },
    filters: {
        getRealTitle(title) {
            return title.slice(0, title.indexOf('+'));
        }
    },
    onMouseover(title) {
        console.log('key: ', title.slice(title.indexOf('+') + 1));
    }
}
</script>
```

**Comment by Gavin-YYC** [comment]
> 那可以把 key 放进 title 里：
> 
> ```
> <template>
>     <s-tree treeData="{{treeData}}">
>         <div slot="title" on-mouseover="onMouseover(title)">{{title | getRealTitle}}</div>
>     </s-tree>
> </template>
> 
> <script>
> import {Tree} from 'santd';
> export default {
>     components: {
>         's-tree': Tree
>     },
>     initData() {
>         return {
>             treeData:  [
>                 {
>                     title: '标题一+0-0',
>                     key: '0-0'
>                 },
>                 {
>                     title: '标题二+0-1',
>                     key: '0-1'
>                 }
>             ]
>         }
>     },
>     filters: {
>         getRealTitle(title) {
>             return title.slice(0, title.indexOf('+'));
>         }
>     },
>     onMouseover(title) {
>         console.log('key: ', title.slice(title.indexOf('+') + 1));
>     }
> }
> </script>
> ```

是个方法
