### ISSUE TITLE
pagination 组件的 pageSizeOptions 设置不生效

### ISSUE THREAD

**Issue by liu354** [ecomfe/santd#87]
pagination 组件的 pageSizeOptions 设置不生效，未按照设置的值展示，依然使用默认值

<img width="839" alt="51c0c1c8fc10ae556595d1419edd33aa" src="https://user-images.githubusercontent.com/33274539/183888212-1bf2010d-965f-40af-8b56-401f137fc1f6.png">

复现路径：
<img width="475" alt="image" src="https://user-images.githubusercontent.com/33274539/183888585-b397df97-4b34-49ff-925f-8b04ee247ea2.png">

<img width="398" alt="image" src="https://user-images.githubusercontent.com/33274539/183888526-7d272761-3dcc-4ac0-aa5a-a45b348097eb.png">
<img width="471" alt="image" src="https://user-images.githubusercontent.com/33274539/183888647-537a50d0-1435-4600-8436-3ba0e12b31f4.png">

**Comment by okaychen** [comment]
给力🚗
