### ISSUE TITLE
Input 点击删除按钮，变为非编辑态，并且触发 blur 事件获取到的是旧的 value 值

### ISSUE THREAD

**Issue by kanglover** [ecomfe/santd#98]
Input 设置 allowClear属性后，点击删除按钮，变为非编辑态，并且触发 blur 事件获取到的是旧的 value 值。

**Comment by kanglover** [comment]
pr: https://github.com/ecomfe/santd/pull/99
参考：
https://github.com/ant-design/ant-design/blob/master/components/input/ClearableLabeledInput.tsx#L58
https://github.com/react-component/input/blob/master/src/Input.tsx#L105

**Comment by bugkiwi** [comment]
#99
